In [2]:
import numpy as np
c=np.array([[2,3,4],[2,5,8]])
c

array([[2, 3, 4],
       [2, 5, 8]])

In [4]:
b=np.array([3,4,5,6,7,8,2])
b

array([3, 4, 5, 6, 7, 8, 2])

In [9]:
n=np.zeros(3)
n

TypeError: Cannot interpret '2' as a data type

In [11]:
m=np.ones(4)
m

array([1., 1., 1., 1.])

In [12]:
v=np.empty(6)
v

array([0., 0., 0., 0., 0., 0.])

In [13]:
## with range of elements
f=np.arange(6)
f

array([0, 1, 2, 3, 4, 5])

In [15]:
# with specific range
b=np.arange(2,10)
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
x=np.arange(2,20,2)
x

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
d=np.linspace(0,30,3)
d

array([ 0., 15., 30.])

In [20]:
#specific datatype in array
g=np.ones(5,dtype=np.int8)
g

array([1, 1, 1, 1, 1], dtype=int8)

In [23]:
g=np.ones(5,dtype=np.int16)
g

array([1, 1, 1, 1, 1], dtype=int16)

In [25]:
j=np.ones(10, dtype=float)
j

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
r=np.zeros((3,4))
r

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
w=np.arange(24, dtype=np.int16)
w

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23], dtype=int16)

In [35]:
w.reshape(3,4,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]], dtype=int16)

In [36]:
w.dtype

dtype('int16')

In [39]:
e=np.ones((3,5,4))
e

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [41]:
n=np.arange(8)
n

array([0, 1, 2, 3, 4, 5, 6, 7])

In [42]:
n<6

array([ True,  True,  True,  True,  True,  True, False, False])

In [43]:
n**2

array([ 0,  1,  4,  9, 16, 25, 36, 49], dtype=int32)

### Arithmetic operations

In [50]:
x=np.arange(2,26,2)
x

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [53]:
x=x.reshape(2,2,3)
x

array([[[ 2,  4,  6],
        [ 8, 10, 12]],

       [[14, 16, 18],
        [20, 22, 24]]])

In [54]:
x.sum(axis=0)

array([[16, 20, 24],
       [28, 32, 36]])

In [55]:
x.sum(axis=1)

array([[10, 14, 18],
       [34, 38, 42]])

In [58]:
x.min(axis=2)

array([[ 2,  8],
       [14, 20]])

In [59]:
np.sqrt(x)

array([[[1.41421356, 2.        , 2.44948974],
        [2.82842712, 3.16227766, 3.46410162]],

       [[3.74165739, 4.        , 4.24264069],
        [4.47213595, 4.69041576, 4.89897949]]])

In [61]:
np.exp(x)

array([[[7.38905610e+00, 5.45981500e+01, 4.03428793e+02],
        [2.98095799e+03, 2.20264658e+04, 1.62754791e+05]],

       [[1.20260428e+06, 8.88611052e+06, 6.56599691e+07],
        [4.85165195e+08, 3.58491285e+09, 2.64891221e+10]]])