# 1-D array

In [3]:
import numpy as np
food=np.array(["smosa","pkora","raita"])
food

array(['smosa', 'pkora', 'raita'], dtype='<U5')

## find type of array

In [4]:
type(food)

numpy.ndarray

In [5]:
price=np.array([5,10,5])
price

array([ 5, 10,  5])

In [9]:
type(price)

numpy.ndarray

## Find length of array

In [7]:
len(food)

3

In [8]:
len(price)

3

## array indexing

In [10]:
food[2]

'raita'

In [12]:
price[1]

10

In [13]:
price[0:]

array([ 5, 10,  5])

In [17]:
price.mean()

6.666666666666667

# zeros

In [18]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# ones

In [19]:
np.ones(4)

array([1., 1., 1., 1.])

# empty

In [20]:
np.empty(5)

array([9.43647655e-312, 9.43647933e-312, 9.43647933e-312, 9.43647933e-312,
       0.00000000e+000])

# arange

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [24]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

# linspace

In [25]:
np.linspace(1,50,num=7)

array([ 1.        ,  9.16666667, 17.33333333, 25.5       , 33.66666667,
       41.83333333, 50.        ])

# specify datatype

In [27]:
np.ones(4, dtype=np.int64)

array([1, 1, 1, 1], dtype=int64)

In [28]:
np.ones(4, dtype=np.float64)

array([1., 1., 1., 1.])

# Array functions

In [38]:
a=np.array([10,4,12.5,5,98,23,87,2,1,44])
a

array([10. ,  4. , 12.5,  5. , 98. , 23. , 87. ,  2. ,  1. , 44. ])

In [39]:
a.sort()
a

array([ 1. ,  2. ,  4. ,  5. , 10. , 12.5, 23. , 44. , 87. , 98. ])

In [40]:
b=np.array([3.4,2,65,23,1,9.3,34,9,45,23.4])
b

array([ 3.4,  2. , 65. , 23. ,  1. ,  9.3, 34. ,  9. , 45. , 23.4])

In [44]:
c=np.concatenate((a,b))
c

array([ 1. ,  2. ,  4. ,  5. , 10. , 12.5, 23. , 44. , 87. , 98. ,  3.4,
        2. , 65. , 23. ,  1. ,  9.3, 34. ,  9. , 45. , 23.4])

In [45]:
c.sort()
c

array([ 1. ,  1. ,  2. ,  2. ,  3.4,  4. ,  5. ,  9. ,  9.3, 10. , 12.5,
       23. , 23. , 23.4, 34. , 44. , 45. , 65. , 87. , 98. ])

# 2-D arrays

In [51]:
a=np.array([[2,4,5,6],[7,3,6,1]])
a

array([[2, 4, 5, 6],
       [7, 3, 6, 1]])

In [52]:
b=np.array([[8,4,6,7],[3,7,2,0]])
b

array([[8, 4, 6, 7],
       [3, 7, 2, 0]])

In [54]:
d=np.concatenate((a,b), axis=0)
d

array([[2, 4, 5, 6],
       [7, 3, 6, 1],
       [8, 4, 6, 7],
       [3, 7, 2, 0]])

In [55]:
e=np.concatenate((a,b), axis=1)
e

array([[2, 4, 5, 6, 8, 4, 6, 7],
       [7, 3, 6, 1, 3, 7, 2, 0]])

In [50]:
c= np.concatenate((a,b))
c

array([[2, 4, 5, 6],
       [7, 3, 6, 1],
       [8, 4, 6, 7],
       [3, 7, 2, 0]])

In [56]:
c.ndim

2

# 3-D array

In [59]:
q=np.array([[[2,3,4],[1,6,3]],
           [[8,1,2],[9,1,6]],
           [[7,3,6],[1,8,3]]])
q

array([[[2, 3, 4],
        [1, 6, 3]],

       [[8, 1, 2],
        [9, 1, 6]],

       [[7, 3, 6],
        [1, 8, 3]]])

In [60]:
q.ndim

3

In [63]:
f=np.array([[3,4,5],
            [6,1,2],
            [5,7,8]])
f

array([[3, 4, 5],
       [6, 1, 2],
       [5, 7, 8]])

In [64]:
f.ndim

2

# find size (number of elements) of array`

In [65]:
f.size

9

In [66]:
q.size

18

In [68]:
q.shape
# first argument displays dmesions, 2nd tells rows in wach dimension and 3rd tells columns in each dim

(3, 2, 3)

# reshape

In [70]:
n=np.arange(9)
n

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [71]:
n.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Covert 1-D array to 2-D

In [72]:
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [73]:
a.shape

(9,)

In [76]:
a.ndim

1

In [74]:
# Row wise
b=a[np.newaxis,:]
b

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [75]:
b.ndim

2

In [77]:
b.shape

(1, 9)

In [79]:
c=a[:, np.newaxis]
c

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [80]:
c.shape

(9, 1)

In [81]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [83]:
a[2:6]

array([2, 3, 4, 5])

In [84]:
a*4

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32])

In [85]:
a+4

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [86]:
a**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64], dtype=int32)

In [87]:
a.sum()

36

In [88]:
a.mean()

4.0